from time import*
import threading
def wite_words(word_count, file_name):
    file = open(file_name, 'w', encoding='UTF-8')
    for i in range(word_count):
        sleep(0.1)
        file.write('Какое-то слово № ' + str(i+1) + '\n')
    print('Завершилась запись в файл', file_name )
time_1 = time()
wite_words(30, 'example1.txt')
wite_words(30, 'example2.txt')
wite_words(200, 'example3.txt')
wite_words(100, 'example4.txt')
time_2 = time()
print('Работа потоков:',time_2 - time_1)
thread_1 = threading.Thread(target=wite_words, args=(10, 'example5.txt'))
thread_2 = threading.Thread(target=wite_words, args=(30, 'example6.txt'))
thread_3 = threading.Thread(target=wite_words, args=(200, 'example7.txt'))
thread_4 = threading.Thread(target=wite_words, args=(100, 'example8.txt'))
thread_1.start()
thread_2.start()
thread_3.start()
thread_4.start()
thread_1.join()
thread_2.join()
thread_3.join()
thread_4.join()
time_3 = time()
print('Работа потоков:',time_3 - time_2)